[package]
name = "z2p"
version = "0.1.0"
license = "MIT"
edition = "2024"

[lib]
path = "./src/lib.rs"

[[bin]]
path = "./src/main.rs"
name = "z2p"

[dependencies]
actix-web = "4.10.2"
config = "0.15.11"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.16.0", features = ["v4"] }


[dependencies.sqlx]
version = "0.8.4"
default-features = false
features = [
    "runtime-tokio",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate"
]


[dev-dependencies]
reqwest = "*"
