app:
  port: 8000
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost:8000"
  sender_email: "test@gmail.com"
  auth_token: "secret-auth-token"
  timeout_ms: 10000
redis_uri: "redis://127.0.0.1:6379"